DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
    id BIGINT generated by default as identity not null,
    name VARCHAR(255),
    created_at timestamp not null,
    CONSTRAINT pk_url primary key (id)
);