DROP TABLE IF EXISTS url_checks;
DROP TABLE IF EXISTS urls CASCADE;

CREATE TABLE urls (
    id BIGINT generated by default as identity NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at timestamp NOT NULL,
    CONSTRAINT pk_url primary key (id)
);

CREATE TABLE url_checks (
    id BIGINT generated by default as identity NOT NULL,
    url_id BIGINT NOT NULL,
    status_code INT,
    h1 VARCHAR(255),
    title VARCHAR(255),
    description TEXT,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT pk_url_checks PRIMARY KEY (id)
);

ALTER TABLE url_checks
    ADD CONSTRAINT fk_url_checks_url_id FOREIGN KEY (url_id) REFERENCES urls (id) ON DELETE CASCADE;
